const usage = () => `Usage: kame <command> [options] [inputfile] [outputfile]

<command>: What to do. Can be 'run' or 'bundle'.

___ Examples: ___

# Runs ./src/index.{tsx,ts,jsx,js} or ./index.{tsx,ts,jsx,js}, whichever exists
kame run

# Runs ./my-script.ts
kame run ./my-script.ts

# Runs ./my-script.ts (same as above)
kame run --input ./my-script.ts

# Bundles:
#   ./src/index.{tsx,ts,jsx,js} or ./index.{tsx,ts,jsx,js}, whichever exists
# into
#  ./dist/index.js
kame bundle

# Bundles ./my-library.ts into ./dist/my-library, and sets up the bundle so
# that if it's loaded in an environment without CommonJS/AMD (eg a browser),
# the exports of ./my-library.ts are put on the global 'MyLibrary'
kame bundle ./my-library.ts ./dist/my-library.js --global MyLibrary

# Run ./my-script.ts, using a custom config (see \`--config\` below)
kame run --config ./my-config.js --input ./my-script.ts

# Bundle ./my-script.ts, using a custom config (see \`--config\` below)
kame bundle --config ./my-config.js --input ./my-script.ts


___ Options: ___

--input: The entrypoint file to run/bundle.

  If left unspecified, kame will attempt to use whichever of these files
  exists, in order:

  - ./src/index.tsx
  - ./src/index.ts
  - ./src/index.jsx
  - ./src/index.js
  - ./index.tsx
  - ./index.ts
  - ./index.jsx
  - ./index.js



--output: The file to write bundle output to.

  This option is only used when bundling code via \`kame bundle\`, not when
  using \`kame run\`.

  If left unspecified, kame will default to './dist/index.js'.

  Note: If you use code splitting (dynamic import), then the split chunks will
  be written into the same folder as the output file, with autogenerated names.
  For this reason, you may want the output file to be in folder like 'dist' or
  'build'.



--watch: Watch for changes and re-run/re-bundle when a change occurs.

  This option will automatically re-run \`kame run\` or \`kame bundle\` when
  any file which is a child of the current working directory changes (except
  for the bundle output file).



--global: The library global name for the UMD wrapper.

  This option is only used when bundling code via \`kame bundle\`, not when
  using \`kame run\`.

  This option specifies the name of the global variable that the bundle
  contents should be written to, if the bundle is loaded in an environment
  without a module loader. If you pass the string "null", then no global will
  be written.

  If left unspecified, no global variable will be written.



--config: Specify a custom load/resolve/evaluate config.

  A kame config can export three functions:

  - load: A custom loader function used to read/transform code.
  - resolve: A custom resolver function used to resolve imports and requires.
  - evaluate: A custom eval function used to run code.

  Each is documented in more detail below.

  If a file named kame.config.js or kame.config.ts exists in the current
  directory, and --config was not specified, kame will behave as if
  '--config kame.config.js' or '--config kame.config.ts' was specified.

  === load ===

  A function which kame will use to read modules from disk and convert
  them to JavaScript.

  A kame config may export a function named "load" that receives a string
  (the file to load), and returns either a string (the code to execute) or a
  { code: string, map: import("kame").SourceMap } object (containing both the
  code to execute and a sourcemap). Load functions must be synchronous, because
  they're called when 'require' is called.

  Note: source maps returned from load functions are not yet supported by
  \`kame bundle\`, only by \`kame run\`.

  By default, 'require("kame").defaultConfig.load' is used, which supports
  ES2020+, React, TypeScript, Flow, CSS, images, and more.

  If you want to write a load function that adds additional functionality on
  top of the default one, or which overrides functionality of the default load
  function, you can require the default config into your config and call it as
  desired:

  \`\`\`
  const {defaultConfig} = require("kame");

  exports.load = function myLoad(file) {
    // whatever custom logic you want.
    // in this example, overriding the default css loading
    if (file.endsWith(".css")) {
      // return your own code in here
    }

    // and then default handling for everything else:
    return defaultConfig.load(file);
  };
  \`\`\`

  === resolve ===

  A function which kame will use to convert the strings appearing in requires
  and imports into absolute paths to files on disk.

  A kame config may export a function named "resolve" that receives two
  arguments:
  - The string that appeared in the require/import
  - The absolute path to the file that that require/import was found in

  By default, 'require("kame").defaultConfig.resolve' is used, which implements
  node's module resolution algorithm, and supports omitting the extension in
  the import/require for any of these filetypes:

    ".js", ".json", ".mjs", ".jsx", ".ts", ".tsx", ".node"

  If you want to write a resolve function that adds additional functionality on
  top of the default one, or which overrides functionality of the default
  resolve function, you can require the default config into your config and
  call it as desired:

  \`\`\`
  const path = require("path");
  const {defaultConfig} = require("kame");

  exports.resolve = function myResolve(source, fromFile) {
    // whatever custom logic you want. in this example, a path alias
    if (source.startsWith("~")) {
      source = path.join(__dirname, source.replace("~", ""));
    }

    return defaultConfig.resolve(source, fromFile);
  };
  \`\`\`

  === evaluate ===

  A function which kame will use to execute code.

  This function is only used when running code via \`kame run\`, not when
  bundling code via \`kame bundle\`.

  A kame config may export a function named "evaluate" that receives two
  arguments:
  - A code string (it will always be an expression)
  - The absolute path to the file where the code came from

  And should return:
  - The result of evaluating the code string

  By default, 'require("kame").defaultConfig.evaluate' is used, which uses
  node's builtin \`vm\` module to run code.

  If you want to write an evaluate function that adds additional functionality
  on top of the default one, or which overrides functionality of the default
  evaluate function, you can require the default config into your config and
  call it as desired:

  \`\`\`
  const {defaultConfig} = require("kame");

  exports.evaluate = function myEval(code, filepath) {
    return defaultConfig.evaluate("var ENV = 'dev'; " + code, filepath);
  };
  \`\`\`



--code-splitting-id: A globally-unique id used for code splitting.

  > This option is only used when bundling code via \`kame bundle\`, not when
  > running code via \`kame run\`.

  A globally-unique id used to tie code-split chunks from this bundle to the
  correct kame instance.

  If you aren't using code-splitting (dynamic imports), you don't need to care
  about this.

  When using dynamic import syntax (\`import()\`), kame splits your code into
  separate files, some of which have generated filenames. These files are
  called "chunks".

  The first chunk that gets loaded is called the "entry" chunk. The entry chunk
  sets up a module cache and loader that other chunks then hook into in order
  to load modules at a later time. This module cache and loader is called the
  "kame instance".

  If your app loads more than one kame bundle that uses dynamic imports, then
  kame needs a way to tell some chunks "go use this kame instance" and other
  chunks "go use that kame instance".

  That's where the code-splitting id comes in. It's a globally-unique
  identifier that can be used to differentiate one kame instance from another.

  When kame compiles a bundle, every chunk in it includes the code-splitting
  id.

  The code-splitting id defaults to an autogenerated unique id. But, if you
  want your chunks to be separately cacheable for browsers (so that unchanged
  chunks don't need to be redownloaded), you'll need to set your own
  code-splitting id.



--loader: Deprecated method for specifying 'load' function. Use \`--config\` instead.
--resolver: Deprecated method for specifying 'resolve' function. Use \`--config\` instead.
--runtime-eval: Deprecated method for specifying 'evaluate' function. Use \`--config\` instead.
`;

export default usage;
